name:  Regions4Countries         
version: 0.0.4
license:      GPL
license-file: LICENSE
#github:       andrewufrank/u4blog.git/daino
maintainer:   Andrew U. Frank <frank@geoinfo.tuwien.ac.at>
author:       Andrew Frank
copyright:    2024 Andrew U. Frank
synopsis: produce statistics for world regions from country data
category: model
description: | 
  Given national statistics data, produce statistics for arbitrary defined regions of the world.
  The region definitions and the statistics are separated from the base library.
   

dependencies:
  - base == 4.*
  - uniformBase
  - containers
  - cassava  #-- csv, sql to observations
  - scientific
  - bytestring
  - vector 
  - text 
  - sqlite-simple
  - filepath 
  - directory

  
library:
  source-dirs: src

executables:
  makedb :
    main: Main.hs
    source-dirs: app/makedb
    dependencies: Regions4Countries 

tests:
  r4c-test:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - Regions4Countries
      - tasty
      - tasty-hunit
      - temporary

ghc-options: 
    -Wall
    -fno-warn-unused-binds 
    -fno-warn-deprecations 
    -fno-warn-unused-do-bind 
    -fno-warn-unused-imports
    -fno-warn-missing-signatures
    -fno-warn-orphans
    -fno-warn-type-defaults 
    -fno-warn-unused-matches 
    -fno-warn-warnings-deprecations   
    -fno-warn-missing-methods 
    -fno-warn-missing-home-modules
    -fno-warn-duplicate-exports 
    -fno-warn-incomplete-patterns 
    -Wno-name-shadowing  
    -Wno-incomplete-record-updates
    # -Wunused-packages  # only useful for clean (after deleting dist)
    
default-extensions: 
    - OverloadedStrings
    - MultiParamTypeClasses 
    - ScopedTypeVariables 
    - DeriveGeneric
    - DeriveAnyClass
    - FlexibleInstances  
    - FlexibleContexts
    - InstanceSigs
